#!/usr/bin/env bash
# build-wasm.sh
#
# Compiles src/math/geometry.cpp into a WebAssembly module.
#
# Prerequisites
# -------------
#   1. Install Emscripten SDK (emsdk):
#        git clone https://github.com/emscripten-core/emsdk.git
#        cd emsdk
#        ./emsdk install latest
#        ./emsdk activate latest
#        source ./emsdk_env.sh        # adds `emcc` to your PATH
#
#   On Windows run:
#        emsdk install latest
#        emsdk activate latest
#        emsdk_env.bat                # or use the Emscripten developer shell
#
#   2. Return to your project root and run:
#        chmod +x build-wasm.sh
#        ./build-wasm.sh
#
# Output
# ------
#   public/geometry.wasm   – raw Wasm binary (Vite will serve it as-is)
#   public/geometry.js     – JS glue file generated by Emscripten
#
# ---------------------------------------------------------------------------

set -euo pipefail

SRC="src/math/geometry.cpp"
OUT_DIR="public"
OUT_NAME="geometry"

mkdir -p "$OUT_DIR"

emcc "$SRC" \
  -O2 \
  -o "$OUT_DIR/$OUT_NAME.js" \
  -s WASM=1 \
  -s MODULARIZE=1 \
  -s EXPORT_NAME="GeometryModule" \
  -s EXPORTED_FUNCTIONS='["_scaleVerticesY", "_malloc", "_free"]' \
  -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap", "HEAPF32"]' \
  -s ALLOW_MEMORY_GROWTH=1

echo "✅  Wasm build complete → $OUT_DIR/$OUT_NAME.wasm  &  $OUT_DIR/$OUT_NAME.js"
